#!/bin/bash
# ====================================================
# Hook pre-commit Git_project
# Vérifie qu'aucun console.log n'est pas présents dans les fichiers .js 
# ====================================================

echo "[Git_project] vérification pre-commits en cours ..."


# Récupérer les fichiers .js modifiés et prêtes pour les commits 
FICHIERS_JS=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$')
if [ -z "$FICHIERS_JS" ]; then
	echo "[Git_project]Aucun fichier Js à vérifier."
	exit 0
fi

RESULTATS=$(grep -n 'console\.log' $FICHIERS_JS 2>/dev/null)

if [ ! -z "$RESULTATS" ]; then
	echo "[Git_project] Erreur : Des console.log ont été trouvés !!! :"
	echo "$RESULTATS"
	echo "Supprimez ou commenter ces console.log avant de commiter."
	exit 1
fi

echo "[Git_project] Vérification OK. aucun console.log trouvé."
exit 0